/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rmiprjclient;

import com.prjrmi.dao.StudentManager;
import com.prjrmi.model.Grade;
import com.prjrmi.model.Student;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abech
 */
public class DisplayStudentDetail extends javax.swing.JFrame {
private final StudentManager stub;
    /**
     * Creates new form DisplayStudentDetail
     * @param stub
     * @param id
     */
   // Integer id;
    private Integer id;
    public DisplayStudentDetail(StudentManager stub, Integer id) {
          this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        this.id=id;
      this.stub=stub;
        initComponents();
        showStudentGrades(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        userDetailTitleLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        addGradeButton = new javax.swing.JButton();
        userDetailPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        fistNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        classroomLabel = new javax.swing.JLabel();
        classRoomField = new javax.swing.JTextField();
        gradeScrollPanel = new javax.swing.JScrollPane();
        gradeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titlePanel.setBackground(new java.awt.Color(255, 255, 204));

        userDetailTitleLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        userDetailTitleLabel.setText("User detail");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(userDetailTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(userDetailTitleLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        addGradeButton.setText("add Grade");
        addGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGradeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(1149, Short.MAX_VALUE)
                .addComponent(addGradeButton)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(addGradeButton)
                .addContainerGap())
        );

        userDetailPanel.setBackground(new java.awt.Color(255, 255, 204));

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        classroomLabel.setText("Classroom");

        classRoomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classRoomFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userDetailPanelLayout = new javax.swing.GroupLayout(userDetailPanel);
        userDetailPanel.setLayout(userDetailPanelLayout);
        userDetailPanelLayout.setHorizontalGroup(
            userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(userDetailPanelLayout.createSequentialGroup()
                        .addComponent(classroomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(classRoomField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userDetailPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fistNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(lastNameLabel)
                .addGap(26, 26, 26)
                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userDetailPanelLayout.setVerticalGroup(
            userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(fistNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classRoomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classroomLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gradesTableModel = new DefaultTableModel();
        gradesTableModel.setColumnIdentifiers(new String[]{"Subject", "Exam Date", "Coefficient", "Grade"});
        gradeTable.setModel(gradesTableModel
        );
        gradeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeTableMouseClicked(evt);
            }
        });
        gradeScrollPanel.setViewportView(gradeTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(gradeScrollPanel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradeScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(112, 112, 112))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classRoomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classRoomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classRoomFieldActionPerformed

    private void gradeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeTableMouseClicked

    private void addGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGradeButtonActionPerformed
            new AddGrade(this.id, stub).setVisible(true); 
    
           
            // TODO add your handling code here:
    }//GEN-LAST:event_addGradeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
  
    
      private void showStudentGrades(Integer studentId) { 
        try {
            Student student = stub.getStudent(studentId);
            System.out.println("Student = " + student.toString());
            
            fistNameField.setText(student.getFirstName());
            
             lastNameField.setText(student.getLastName());
            classRoomField.setText(student.getStdClassName());
           
            List<Grade> grades =student.getGrades();
            if (grades != null){
            for (Grade grade : grades) {
                System.out.println("Grades = " + grade.toString());
                gradesTableModel.addRow(new Object[]{
                    grade.getSubjectName(),
                    grade.getExamDate(),
                    grade.getCoef(),
                    grade.getGrade()
                });
            }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur lors de la récupération des détails de l'étudiant: " + e.getMessage(),
                                          "Fetch Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
      
    private DefaultTableModel gradesTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGradeButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JTextField classRoomField;
    private javax.swing.JLabel classroomLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField fistNameField;
    private javax.swing.JScrollPane gradeScrollPanel;
    private javax.swing.JTable gradeTable;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel userDetailPanel;
    private javax.swing.JLabel userDetailTitleLabel;
    // End of variables declaration//GEN-END:variables
}
